version: '3'

services:
    app:
        image: cruzesqueisso/fullcycle-frontend:v1
        container_name: frontend-app
        ports:
            - 3001:3001
        extra_hosts: 
            - 'host.docker.internal:172.17.0.1'
