version: '3'

services:
    backend:
        image: cruzesqueisso/fullcycle-backend:v1
        container_name: backend-service
        ports:
            - 3000:3000
    frontend:
        image: cruzesqueisso/fullcycle-frontend:v1
        container_name: frontend-app
        ports:
            - 3001:3001