version: '3'

services:
    app:
        image: cruzesqueisso/fullcycle-backend:v1
        container_name: backend-app
        ports:
            - 3000:3000
        extra_hosts: 
            - 'host.docker.internal:172.17.0.1'